language: ruby
rvm:
- 2.0.0
bundler_args: "--without production"
addons:
  postgresql: '9.3'
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate --trace
script:
- bundle exec rspec
notifications:
  email:
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: edxVV1A4KGdG8TwZpRntCQkc4F338Z/Ee9ZfHkesqQPpD9Km+9m5Tkhfl6d/XS1EMSdodfw6NqjQ6Z6B44SHhXWyC+fvA0OIh2r8d3sZytxBLfiRupn7Niwg9/p2vv4E5wmJ3VwQdGVK4zNXLWK43PKdQtH/LNbX6fdXt9U1fm7kE5Ka3MhNUyqbvX0/PgNy5n+ldoZq1kw4fEwFw8NTGgsys9kH0X3OmDuueYAbcAlW6pJSRIhMSPM2cLNluMjv1i717P3KQ+CzlMy85HL3zd+waqEvpcEoChTxmoZFGArJoWsQjBbKt6E1ipd49IYGn5LeBPDD0u2CVjaIYzPj1KR6T/af3KJ4OLEXyAtf/JnoDxGaSQH5q1upoPlBhP8rdArlRKlxscw8D8H7V+Srh/AMwbcYuvsif7DVGqESRismt4OjA2uOlQ1RKif4OaGfLDR/CwYUXxxf7hXlpzHT/tNZtwf1KEwh7cuZA7uqXi8yHMBSiuRi9ovuOfyVGQEtpOg1cKb4KSANXSrsb1SEgpbm72NbKxQhBIA7dcBIgmVMup3TTnhbaGHaIkNpzI8emfsjbMhH7GErZ8HsW3FnbH/sDXTE3PRfsYaSGbFIHy65S44f4d2j97v+1y7T/mTKyqRtI7lmIQUaVYkVy2t4Wxx0RX8s8VJ7KHgVq4gzAjU=
  app: blooming-eyrie-75780
  on:
    repo: jfonso/shoeaddict_app
  run: rake db:migrate
env:
  global:
  - secure: MWNCo4rJW60Fck33IrMMH0F/PjWwWnP9nyVunORmGcEyvGOxgnwr2A1wfrUoHjflUi7HcbC54jdzY+mIBM7nyrR3+TxYu5UzDJ/MO6wEqBg8TtV5PACH2mW4DrCB7zazi0KvomKSRK2KZSFcBnjp29a8gX78fpuPr4pgjjx4cFp/KGYbl3igCxdlK4cr9l4VxGFfgIGyMu7TcPEAhO2fEf/2yXxE8Y28uZWhtJ7w1yOaASOAoF8lSvhFBdj2G+i0tAMnFPeHfbsYAVhK2ZxwmAM+BVVvFIQKx8JIyyt311KZbSoB7SXNtFxHnzz8ZMpwPSaXL56qqJdShjBfeJSTBPtLqms/1iExFzno9PIq5F9YvPQqJUadat9WQf0GadHQStvGjREhEi0k93HdO9GjqrU7H5BaNYjWf8pdv/sTvRaf4oMsb4ldOLNDlu59qHzwyt9pHeQ7PeFkN7qzIXDgUFSbQXKMmkeC6h00uNI7earJQgwvGT/IWJFLbo2/smSFf2IW5a3qX1JRQaDoVfhH9KkLTkzmrCviGRKvhfu3spa7jKwDWGfTmZvb1d3PwPy+ivnlJo/jOpLtgJySQxPUkAftXc4sbnf67Xsy9jin405eKePGHmcm87Yv93iUPYMVfPHlZXYNeK8OeG2FtU39sebOBHPLq4LbTvqdvLPMRPA=
  - secure: fog0pojetXMLcswzBXCIU339uMU/GGIMjH/ZPAqL34E5XbpMNXp17DnllRme2D7sNxRyUZYACRdQo0leJIiRBedvpdHaTU/H3HnVt0GNoUWHEbdb6F/qdcn3s0guhwV3ITNNsckSxKpW9OijkV8ntZtHlqXthqunO30DUg6r3V1nK6AlO4eIi7wYkyqyMzCBo3wqsJWwAG1Ijj5XGCEXSC34/FIC+tEtGwLjJpQxojgeGVHp+2YIBEk7iEjkpdd9em4dU08BZl9PYJv1HNp8HKyy5XLVxtZPtK3F4t/XmD4ROR4on/FKulDt8G5vEL3/rFD3jGtr+uXNZxz9bAWNMXUtSaddXGyJAR0ujJhiynVI/HCsgUqRv284lP7nc77af9zJLoZduIGjqoLN8uTC497cJ5obAO+IvrOX9ETuRLu1qQgH/Zxb3zogYwVvChs85byJnvWlMjXp+dF8WsIswuGYCqqGMSHbEcOM2z48sIsVMaGvWZhjmpH/uqEYChX3UntxeG+SO0N1wVuZCUtEPmFWlf0P4uT90aLkEzgQAJdy7sz8gqADFw40hfUomA9LCUYAPF3AuMHHuelsfsSHagyOV3TtzIxkAXI4RBmp0bGgkhBtd0GLBPXJfD2/DYDv+LRc1JcPPpfm6UVipuv7f2I862KdGBCtO5yNPI98PHg=
